[package]
name = "turbopuffer-bench"
version = "0.0.0"
edition = "2024"


[dependencies]
anyhow = "1.0.100"
env_logger = "0.5"
reqwest = { version = "0.12.24", features = ["json"] }
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
