name: Generate report

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

env:
  TURBOPUFFER_API_KEY: ${{ secrets.TURBOPUFFER_API_KEY }}

jobs:
  report:
    name: Generate report

    runs-on: blacksmith-32vcpu-ubuntu-2404

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Check out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Check out tpuf repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          repository: turbopuffer/turbopuffer
          path: turbopuffer
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165
        with:
          distribution: temurin
          java-version: "21"

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c

      - name: Launch turbopuffer
        run: |
          # Install OpenBLAS.
          sudo apt-get update
          sudo apt-get install -y libopenblas-dev

          # Make fake cache directory.
          sudo mkdir -p /mnt/disks/localssd/tpuf-staging-cache
          sudo chown $USER /mnt/disks/localssd/tpuf-staging-cache

          # Set up devbox-like environment.
          cd turbopuffer
          source devbox/env.sh
          # TODO: use a machine that supports the CPU features we use in
          # production.
          export RUSTFLAGS="-C target-cpu=native --cfg tokio_unstable"
          # Temporary override to enable all block-based settings.
          sed -i 's/^\(enable_block_based_[^=]* = \).*/\1true/' settings/default.toml

          # Build and run tpuf.
          cargo build --release --bin tpuf
          cargo run --release --bin tpuf server &> tpuf.log &

          # Wait for tpuf to become available.
          # TODO: do this more robustly.
          sleep 1

      - name: Cache corpus
        id: cache-corpus
        uses: actions/cache@v4
        with:
          path: corpus.json
          key: corpus

      - name: Download corpus
        if: steps.cache-corpus.outputs.cache-hit != 'true'
        run: make corpus

      - name: Compile engines
        run: make compile

      - name: Build indexes
        run: make index

      - name: Trigger full compaction
        run: |
          # Only works with the test API key where the API key *is* the org ID.
          cargo run --release --bin tpuf -- prompt-full-compaction $TURBOPUFFER_API_KEY search-benchmark-game
          # reindex <org_id> <namespace> <from_scratch> <force>
          cargo run --release --bin tpuf -- reindex $TURBOPUFFER_API_KEY search-benchmark-game false true

      - name: Run benchmarks
        run: make bench

      - name: Publish results
        run: make publish
        env:
          GIT_AUTHOR_NAME: turbobot
          GIT_AUTHOR_EMAIL: bot@turbopuffer.com
          GIT_COMMITTER_NAME: turbobot
          GIT_COMMITTER_EMAIL: bot@turbopuffer.com

      - name: Upload turbopuffer logs
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always()
        with:
          path: tpuf.log

      - name: Upload GitHub Pages artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e
